### ISSUE TITLE
Number of items to replace is not a multiple of replacement length

### ISSUE THREAD

**Issue by williamhoole** [EcoDynIZW/imageseg#2] opened 2022-11-29 09:56 UTC
I get the following error when converting images to Keras input: 

Error in array_out[i, , , ] <- images_proc[[i]] : 
  number of items to replace is not a multiple of replacement length

The images are PNG format and are RGB.

how do I fix this ?

**Comment by williamhoole** [comment] 2022-12-06 09:52
Hi, 

i have imported 1500 PNG images using imageseg:

train <- loadImages(imageDir = train_dir)

the images are RGB and would like to use all 3 color channels for training but 
when I run this line, I get the error mentioned above.
x_train <- imagesToKerasInput(train, type = "image", grayscale = FALSE)

but if I change grayscale to TRUE I do not get the error.

**Comment by jniedballa** [comment] 2022-12-16 17:37
If you don't mind, can you please share a reproducible example with your png files? I can't tell from the error what the problem is (but as you pointed out probably related to the colorspace), so I'd need to test it to fix. If a small subset of the 1500 png images is enough to demonstrate the error, even better. Feel free to share a link with your data privately to the package maintainer email address. 
Thank you

**Comment by jniedballa** [comment] 2023-11-17 07:27
Closing this for now. Feel free to reopen with a reproducible example.

**Closed by jniedballa** 2023-11-17 07:27 UTC
